# Generated by Django 3.2.9 on 2021-11-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211103_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachments',
            field=models.ImageField(null=True, upload_to='attachments'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
